### ISSUE TITLE
Strange NS_ERROR_UNEXPECTED in CommandPatch.prototype.queryState

### ISSUE THREAD

**Issue by valberg** [guardian/scribe#208]
I wrote this to the maillist, but decided to make it into an actual issue since I've narrowed the problem a bit more down.

I'm using Firefox 30.0 on Mac OS X, and sometimes I get this strange error in the console: `NS_ERROR_UNEXPECTED:` and nothing more.

It says that it happens at line 3669 in scribe.js:

```javascript
CommandPatch.prototype.queryState = function () {
  return document.queryCommandState(this.commandName);  // line 3669
};
```

I've figured out that the error can be "omitted" with the following:

```javascript
CommandPatch.prototype.queryState = function () {
  if( this.commandName == 'insertUnorderedList' || this.commandName == 'insertOrderedList') {
      return false
  }
  return document.queryCommandState(this.commandName);
};
```

So somehow the list commands are forcing Firefox to throw an `NS_ERROR_UNEXPECTED`. Sometimes it's even `NS_ERROR_FAILURE`. But both cases have no more information associated.

Refrence to errors in Firefox: https://developer.mozilla.org/en-US/docs/Table_Of_Errors

**Comment by zbyte64** [comment]
I had this issue on FF35/Ubuntu 14.04 , I was using this with react and I think it was rewriting the toolbar elements. When I properly specified key attributes in react the error stopped as the elements were no longer being overwritten.

**Comment by zbyte64** [comment]
Never mind, still have the issue :(
At this point I am just checking if the error message is this and suppressing the error if it is.
