### ISSUE TITLE
Pressing shift-enter for newlines doesn't advance cursor

### ISSUE THREAD

**Issue by bradvogel** [guardian/scribe#229]
See video below. Repro steps:
1. Go to http://guardian.github.io/scribe/
2. Place cursor after the "!"
3. Press shift-enter to add newlines

Notice that the cursor stays on the next line and doesn't move down when the newlines are being added. Tested on Chrome 35 on OS X.

It doesn't happen in a regular contenteditable field in the same browser.

![bug](https://cloud.githubusercontent.com/assets/821706/3520322/e8f834d4-072d-11e4-87bd-f308897c2515.gif)

**Comment by kof** [comment]
Also the prob is that in block elements mode, browser inserts br's instead of p's. This is an issue for me too.

**Comment by kof** [comment]
Why do we have brs if allowBlockElements: true first of all?

**Comment by kof** [comment]
@OliverJAsh if you help with the plan how to avoid brs in block mode, I could send a PR.

**Comment by kof** [comment]
I would suggest we need to:
- place marker
- split html by marker
- create new paragraphs for each part
- replace current paragraph by new paragraphs

**Comment by bradvogel** [comment]
Looks like this is fixed. Thanks!
