### ISSUE TITLE
Feature request: 'paste' formatter type

### ISSUE THREAD

**Issue by bradvogel** [guardian/scribe#241]
Currently sanitizers that use `scribe.registerHTMLFormatter('sanitize', ...)` will sanitize both content that's pasted as well as content that is programmatically added to the editor.

However, I'd like to handle these cases separately. I'd like pasted content to be sanitized to a stricter subset of allowed tags than content that I programmatically inject into the editor. For example, I have code that adds divs to the editor, but I don't want someone to be able to paste them in.

My current workaround is to take over handling the 'paste' event from scribe. I sanitize the content and then place it into the editor at the cursor position.

I'd like to propose a new HTML Formatter type that is called by in Scribe's 'paste' handler that will give client code an opportunity to sanitize only pasted content. Example code would look like:

```
scribe.registerHTMLFormatter('paste', function(html){ return sanitizePastedContent(html); });
```

I can file a PR for this if this proposal is OK with you.

**Comment by bregenspan** [comment]
I'm working on adding a paste helper to the test harness, and can add tests for paste formatter changes once that's ready: https://github.com/gawkermedia/scribe-test-harness/compare/add-paste-helper?expand=1

Past helper is not behaving in Chrome for me but I believe the test suite just generally doesn't work there atm?
