### ISSUE TITLE
Go through the plugins and remove their dependency on Scribe Common

### ISSUE THREAD

**Issue by hmgibson23** [guardian/scribe#291]
Now that scribe common is no longer separate from Scribe, it will be worth going through all the plugins that use it and updating them accordingly.

See [this](https://github.com/guardian/scribe-plugin-curly-quotes/pull/15) for an example.

* https://github.com/guardian/scribe-plugin-curly-quotes
* https://github.com/guardian/scribe-plugin-intelligent-unlink-command
* https://github.com/guardian/scribe-plugin-smart-lists

**Comment by rrees** [comment]
All the plugins have now been updated so post the newsroom rollout I will need to update the dependencies on Scribe and Composer

## Update Scribe example

- [ ] Curly quotes
- [ ] Intelligent unlink
- [ ] Smart lists
