### ISSUE TITLE
Behavior when inserting contenteditable="false" elements

### ISSUE THREAD

**Issue by christopherliu** [guardian/scribe#308]
I'm using contenteditable="false" elements in my editor pane to represent atomic elements (a chart, for example, might have a DOM but we'd want to delete it all at once). While I was looking at the code, I noticed that certain areas use the existence of the contenteditable attribute as a proxy for the Scribe container.

https://github.com/guardian/scribe/blob/master/src/api/selection.js:23
https://github.com/guardian/scribe/blob/master/src/api/node.js:15

**Comment by theefer** [comment]
> just select the scribe element itself

:+1:

**Comment by rrees** [comment]
@christopherliu I believe this should be fixed in 1.2.4
