### ISSUE TITLE
Requiring immutable.js breaks scribe-plugin-noting

### ISSUE THREAD

**Issue by cutandpastey** [guardian/scribe#311]
When scribe references immutable.js like this:

`'immutable/dist/immutable'`

I get:

`Uncaught Error: Script error for: immutable/dist/immutable
http://requirejs.org/docs/errors.html#scripterror`

when trying to run the test suite within the noting plugin.  Ive patched this within the plugin but would be good to get a fix in this codebase.  I'd love to PR this as it's quite a simple fix but an unwilling because of https://github.com/guardian/scribe/issues/310

**Comment by rrees** [comment]
This is fundamentally an issue with the way we bring Scribe into our plugins for testing. The real answer is to switch from using master to using Bower versioned releases but that's a big undertaking that probably needs to be whittled away rather than addressed in a single issue.
