### ISSUE TITLE
Document scribe.targetWindow and scribe.targetDocument

### ISSUE THREAD

**Issue by hmgibson23** [guardian/scribe#317]
This https://github.com/guardian/scribe/pull/290 PR relates to these and would be nice to have some documentation for them.

**Comment by bregenspan** [comment]
It might also be useful to document why someone might want to use an IFRAME for their editor area, or even recommend it as the default way to go. http://stackoverflow.com/a/11222149/69697 seems like a good list but leaves out possible performance benefits (a likely one is avoiding full-DOM reflows/repaints when changes are made within the editor).

**Comment by rrees** [comment]
Since ultimately we couldn't support ShadowDOM as yet. Closing.
