### ISSUE TITLE
How do you .setContent without triggering a change event?

### ISSUE THREAD

**Issue by christopherliu** [guardian/scribe#326]

**Comment by hmgibson23** [comment]
You can't currently. We always trigger a ```content-changed``` event. What's the use case?

**Comment by christopherliu** [comment]
I share an editor instance in a multi-document editing environment and so I reset the content every time we switch selected document.

I remove the content-changed event when switching so it's not a huge deal, but I've been getting errors on Firefox every time we switch documents, stemming from that event somehow, so I thought disabling the event would be easier than trying to diagnose the error. Guess I'll just diagnose the error...
