### ISSUE TITLE
Patch Firefox bug for 'insertOrderedList' breaking <div contenteditable> inside <foreignobject>

### ISSUE THREAD

**Issue by danburzo** [guardian/scribe#365]
I've just logged [a bug on Mozilla's Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1147485). 
It seems that calling `document.execCommand('insertOrderedList', false, null)` in an editable DIV that's set up like this:

```html
<svg width='600' height='200'>
  <foreignObject x='0' y='0' width='100%' height='100%'>
    <div contenteditable='true'>
       Some content here
    </div>
  </foreignObject>
</svg>
```
will break the DOM (you'll see there are _three_ (!) separate SVGs in the document now).

You can [test it here](https://bug1147485.bugzilla.mozilla.org/attachment.cgi?id=8583182) -- just put the cursor on _With focus here, it should not work._, and press Ctrl+A (I've mapped it to the offending command).

Since this is not directly Scribe-related, is it appropriate to work around this bug in Scribe? If so, are there any other parts where a Command patch completely forgoes `document.execCommand` in favor of completely custom behavior?

__Note:__ Tested in Firefox 36.0.4 on Mac OS X.

**Comment by rrees** [comment]
I think we'd be happy to take a patch on this (ideally with a test that will fail when Mozilla fixes the bug) I'm not sure we would feel the pain enough to fix ourselves as a priority.

**Comment by danburzo** [comment]
Hi Robert, I totally understand and it _is_ quite a narrow case. For our specific case, it was better to patch this outside Scribe, so I guess I should just close this. 

In case anyone else stumbles upon the problem, we solved it by:

1. extracting the `<div contenteditable='true'></div>` from the `<foreignObject>`
2. creating a new parent node for it, which is then inserted directly into the `<body>` element
3. the new parent can mimic the position of the `<foreignObject>` by applying the latter's screen transform matrix (`foreignObject.getScreenCTM()`) as a CSS transform.
4. when finishing the edit, put the `<div contenteditable='true'></div>` back inside its parent `<foreignObject>` and destroy the temporary div created at step 2

(If anything, I can provide a more detailed explanation)

**Comment by josh-infusionsoft** [comment]
This is a problem I am running into as well. I have attempted to mimic the functionality of document.execCommand('insertOrderedList', false, null) with a custom plugin which has its own challenges.

I am not sure how much I like the solution provided here but I wanted to at least make it known that others are running into this problem.
