### ISSUE TITLE
`EventEmitter.prototype.off` doesn't work

### ISSUE THREAD

**Issue by rf-** [guardian/scribe#370]
Relevant code:

``` javascript
  EventEmitter.prototype.off = function (eventName, fn) {
    var listeners = this._listeners[eventName] || Immutable.Set();
    if (fn) {
      listeners = listeners.delete(fn);
    } else {
      listeners = listeners.clear();
    }
  };
```

Assigning to the local `listeners` var doesn't actually affect the value of `this._listeners[eventName]`.

**Comment by rf-** [comment]
I would start opening PRs for this stuff, but right now I don't have a working dev environment for Scribe set up. I'll try to do that soon.

**Comment by cutandpastey** [comment]
@rf- Thanks for the heads up, fixed in https://github.com/guardian/scribe/pull/372.
