### ISSUE TITLE
Having an `<em>` tag in the edited text breaks some commands

### ISSUE THREAD

**Issue by rf-** [guardian/scribe#371]
This looks related to 345ef2d3a43e2b65c8b87ad2d31b5677bf61f563, specifically this code:

``` javascript
      // Get scribe previous content, and strip markers.
      var lastContentNoMarkers = scribe._lastItem.content
        .replace(/<em class="scribe-marker">/g, '').replace(/<\/em>/g, '');

      // We only want to push the history if the content actually changed.
      if (scribe.getHTML() !== lastContentNoMarkers) {
```

Because lastContentNoMarkers is missing all `</em>`s, not just the ones with the `scribe-marker` class, the comparison fails.

To repro the specific symptom I'm seeing, go to the Scribe demo page, paste in some HTML containing an `<em>`, and then click either the bold or italic buttons without having a range of text selected.

**Comment by rrees** [comment]
@rf- can you retest with 1.3.7?

**Comment by rrees** [comment]
Closing as presumed fixed
