### ISSUE TITLE
Paste on ie11

### ISSUE THREAD

**Issue by growlsworth** [guardian/scribe#391]
pasting content does not work in IE11. This can be reproduced in the example: https://guardian.github.io/scribe/

I suspect it has to do with the polyfill for insertHTML that is not supported in IE as is described in this earlier PR: https://github.com/guardian/scribe/pull/159#issuecomment-42691617 . Thanks Guardian!

**Comment by rrees** [comment]
Hi @growlsworth we don't officially support IE for Scribe. We will accept patches if they work with our target browsers although we don't have IE in our CI configuration.

**Comment by growlsworth** [comment]
That's a bummer and I totally understand the decision. Thanks for the update.
