### ISSUE TITLE
Consolidating node operations

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/scribe#397]
Hello,

Right now DOM-related operations are scattered all over: in ./node.js, ./element.js, ./api/node.js, ./api/children.js and sometimes in core plugins (think `unwrap`, `insertAfter`, `hasContent`, etc.). Plus ./api/node.js defines a class with a link to a DOM node: this can be a source of memory leaks if objects are never released (in closures for instance).

I could survey the code, make an inventory of all DOM-related operations and put everything into a single AMD module (./node.js). This would increase consistency, remove redundant code, which means more optimized code and an overall happier browser :-)

How does that sound?

**Comment by hmgibson23** [comment]
Sounds good to me!

**Comment by regiskuckaertz** [comment]
@hmgibson23 great! I'm on it.

**Comment by regiskuckaertz** [comment]
This is going to be a biggie, I'll split this into multiple PRs for everyone's sake :-)

**Comment by rrees** [comment]
Are we okay to close this one now?

**Comment by regiskuckaertz** [comment]
Yes of course.
