### ISSUE TITLE
ImmutableJS version

### ISSUE THREAD

**Issue by Carlsson87** [guardian/scribe#400]
scribe-editor is currently depending on version ~3.6.2 of ImmutableJS, which results in version 3.6.4.

On line 11 in `src/element.js` the method `includes` of ImmutableJS's Set is used. This method does not exist in any 3.6.* version, it was added in 3.7.1.

Either require a more recent version of Immutable, or use it's alias `contains`.

Related issue on their repo: https://github.com/facebook/immutable-js/issues/499

**Comment by regiskuckaertz** [comment]
+1 saw that too yesterday

**Comment by rrees** [comment]
Yes, this was updated in Bower but not in the NPM dependencies

**Comment by rrees** [comment]
Published v1.4.5 which should be in sync, @Carlsson87 can you check?

**Comment by Carlsson87** [comment]
Perfect. Good job.
