### ISSUE TITLE
Clipboard paste

### ISSUE THREAD

**Issue by alexeygolev** [guardian/scribe#401]
Getting "event.clipboardData.types.contains is not a function" when attempting to paste. The same here http://guardian.github.io/scribe/. Chrome 43.0.2357.130,  45.0.2439.0 canary, Opera 30.0.1835.59, Safari 8.0.6. Works in Firefox though

**Comment by hntrdglss** [comment]
I'm experiencing the same, using the NPM release with webpack.

**Comment by rrees** [comment]
@alexeygolev I've deployed 1.4.6 to the Github pages, can you retest?

**Comment by rrees** [comment]
@alexeygolev @cutandpastey @regiskuckaertz Regis pointed out that FF might not be Array-like so the fix may have broken FF. Can you check?

We might need to use a fixed data structure to reconcile the behaviours (at least I understand why the Lodash function was being used now).

**Comment by alexeygolev** [comment]
@rrees it indeed did break in FF. Works in Chrome, Opera and Safari

**Comment by rrees** [comment]
@alexeygolev Okay, I have taken on your suggestion and this should now work for all browsers (release 1.4.8 or later).

**Comment by rrees** [comment]
@alexeygolev I think release 1.4.13 might be the definitive solution for this. Do you want re-test and confirm?

**Comment by alexeygolev** [comment]
@rrees yep... works across the browsers...cheers
