### ISSUE TITLE
JS error on each keystroke coming from scribe-plugin-smart-lists.js

### ISSUE THREAD

**Issue by trevordixon** [guardian/scribe#408]
`Uncaught TypeError: Cannot read property 'isBlockElement' of undefinedfindBlockContainer @ scribe-plugin-smart-lists.js:26`

![scribe](https://cloud.githubusercontent.com/assets/1253245/8398734/fa0fd850-1daf-11e5-99a8-ac98c07c0c14.gif)

**Comment by regiskuckaertz** [comment]
@rrees My previous PR introduced a backwards-incompatible change by removing `scribe.element`. I thought about going through all the plugins I knew of, but I find adding it back as an alias of `scribe.node` and mark it as obsolete would be a better fit. If that's fine with you, I'll submit a PR asap.

**Comment by rrees** [comment]
@regiskuckaertz Okay, sounds good but it's probably worth changing the plugins as well

**Comment by rrees** [comment]
@trevordixon this should be fixed now, can you confirm?

**Comment by trevordixon** [comment]
Yep, no more error.
