### ISSUE TITLE
Text colours and the toolbar plugin

### ISSUE THREAD

**Issue by SgtOddball** [guardian/scribe#420]
Is there currently a way to edit the colour of text (in the same way strikeout can be used for example) highlighted through the tool bar or is it something not currently available either as a default or 3rd party plug-in? 

I'm just wanting to make sure I've not missed something blindingly obvious before I look further into this.

**Comment by hmgibson23** [comment]
There's nothing I'm aware of but this would be pretty trivial to implement as a plugin.
