### ISSUE TITLE
Determine keydown event when execute is called

### ISSUE THREAD

**Issue by josh-infusionsoft** [guardian/scribe#425]
I am creating a plugin and there is a certain case where execute is called by either [enter or backspace] (https://github.com/guardian/scribe/blob/master/src/plugins/core/events.js#L163) in a list and I need to know which key it was.

Is there a known way to get this information (must work in FF and chrome)? Or will I need to modify scribe in order to accomplish this?

**Comment by josh-infusionsoft** [comment]
Here is my attempt at a fix. If you have a better suggestion I would love to hear it:

https://github.com/guardian/scribe/pull/428

**Comment by rrees** [comment]
Please test release v2.0.1 and close if fixed. Thanks for the PR.
