### ISSUE TITLE
bower install doesn't install needed plugins (also with --save-dev)

### ISSUE THREAD

**Issue by srad** [guardian/scribe#432]
When I follow the readme.md and run an installation via ```bower install scribe``` and load scribe with require-js then I get straight missing plugin errors:

```
logger....0746263 (Zeile 92)
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/plugins/core/plugins.js?ver=1443300746263"
plugins...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/plugins/core/formatters.js?ver=1443300746263"
formatt...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/plugins/core/commands.js?ver=1443300746263"
command...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/plugins/core/events.js?ver=1443300746263"
events....0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/api.js?ver=1443300746263"
api.js?...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/plugins/core/patches.js?ver=1443300746263"
patches...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/undo-manager.js?ver=1443300746263"
undo-ma...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/event-emitter.js?ver=1443300746263"
event-e...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/transaction-manager.js?ver=1443300746263"
transac...0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/config.js?ver=1443300746263"
config....0746263
"NetworkError: 404 Not Found - http://localhost/demo/js/src/vendor/scribe/node.js?ver=1443300746263"
```

Leaving aside that you use relative paths in your modules which has to be handled in the require.config with a package definition (which is not mentioned).

Whatever, I tried to install the plugins separately but of course the paths are not correct anymore and I don't want to redirect every plugin in the require.paths definition.

Is there a sane way to make your project work with requirejs and bower?
Do I need to install a certain branch/version/whatever?

**Comment by rrees** [comment]
You're right that we don't go into the require config in the readme. Maybe something we should add to the wiki...

However I think your problem is related to the require setup since it is failing to load the individual Scribe source files. What do you have 'scribe' aliased as?
