### ISSUE TITLE
Paste does not work on android

### ISSUE THREAD

**Issue by crasu** [guardian/scribe#433]
Pasting text into scribe does not work for me on android 5.x. 

The mobile chrome paste event does not contain the pasted content in event.clipboardData.types. However the code around line 188 in events.js seems to expect this. Adding a check event.clipboardData.types seems to fix the issue. 

Would you merge a pull request for this issue even if mobile chrome is not officially supported?

**Comment by rrees** [comment]
@crasu happy to take a pull request but obviously as it would not be in the test suite it might be vulnerable to regressions. Add a comment on the check to make clear why it is there.

**Comment by crasu** [comment]
see #434
