### ISSUE TITLE
HTMLFormatters: Normalize before Sanitize?

### ISSUE THREAD

**Issue by gpbmike** [guardian/scribe#444]
I'm trying to use the [sanitizer plugin](https://github.com/guardian/scribe-plugin-sanitizer) together with the [semantic elements plugin](https://github.com/guardian/scribe-plugin-formatter-html-ensure-semantic-elements). The sanitizer plugin runs during the 'sanitize' phase before the semantic elements plugin runs in the 'normalize' phase.

``` javascript
  HTMLFormatterFactory.prototype.format = function (html) {
    var formatters = this.formatters.sanitize.concat(this.formatters.normalize);

    var formatted = formatters.reduce(function (formattedData, formatter) {
      return formatter(formattedData);
    }, html);

    return formatted;
  };
```

https://github.com/guardian/scribe/blob/a62186405271aa52c131ab8313a4f5f027096d6d/src/scribe.js#L322-L330

My problem is that if I pass `<p><b>hello</b></p>` into Scribe, the sanitizer plugin (with `strong` whitelisted, but not `b`) will be run first and strip out the italics tag resulting in `<p>hello</p>`. Ideally I would be able to switch out the `<b>` tag for a `<strong>` tag before the sanitize phase. If I whitelist both `strong` and `b`, `<p><strong>hello</strong><p>` is the result but that doesn't feel right. Is that the best way? Any suggestions?

**Comment by rrees** [comment]
Maybe we should allow configuration to override the ordering.

**Comment by gpbmike** [comment]
Is there a case to maintain separate 'sanitize' and 'normalize' phases? Could all HTMLFormatters be run in the order they are added?

```javascript
scribe.use(firstFormatter);
scribe.use(secondFormatter);
```
