### ISSUE TITLE
Configuring options via a plugin

### ISSUE THREAD

**Issue by chrishutchinson** [guardian/scribe#446]
Hey folks,

I'm pretty sure I'm missing something, but have trawled through various plugins and haven't been able to see a solution.

I want to change the `allowBlockElements` option depending on some specific configuration I have (I'm running multiple Scribe instances). 

This is my plugin code at present, but it doesn't actually change the value of `scribe.options.allowBlockElements`. What am I missing?

    var ScribeBlockElementsPlugin = function() { 
        return function(scribe) {
            // ...
            scribe.options.allowsBlockElements = false;
            // ...
        };
    };

**Comment by rrees** [comment]
Off the top of my head I think this is correct as options should be immutable once Scribe is in action. Can you run your logic when generating the options block for the initialiser?

**Comment by chrishutchinson** [comment]
Cheers @rrees! Kept digging and found the `Object.freeze()`. Thanks for clarifying.

We initially didn't think we could change the configuration before initialisation, but have figured out a solution! Thanks, this can be closed.
