### ISSUE TITLE
Undo manager cannot be disabled

### ISSUE THREAD

**Issue by nedrocks** [guardian/scribe#452]
If I set undo to disabled, scribe complains because _lastItem is null and part of the constructor calls setHTML which has a call for

`_lastItem.content = <whatever>`

There needs to be an else block to allow for this. Currently, my work around is to simply set

`Scribe.prototype._lastItem = {content: ''};`

**Comment by rrees** [comment]
Okay good spot, I'll take a look. `setHtml` should probably respect the option.

**Comment by rrees** [comment]
@nedrocks do you want to review the associated PR
