### ISSUE TITLE
Logic bug in node.removeChromeArtifacts()

### ISSUE THREAD

**Issue by mindplay-dk** [guardian/scribe#464]
Possible logic bug [here](https://github.com/guardian/scribe/blob/master/src/node.js#L142):

```
      if (!node.getAttribute('style')) {
        node.removeAttribute('style');
      }
```

I'm not sure what this was intended to do, but it appears to say, "if the node doesn't have the attribute, remove the attribute" - I'm not sure what the intent was, but I don't think this code does anything?

**Comment by rrees** [comment]
@regiskuckaertz do you remember what this code was trying to achieve?

**Comment by regiskuckaertz** [comment]
@rrees Javascript and type coercion... the empty string is `false` in JS: this code was meant to eliminate instances of `\<elem style="">`. At least that's what I think.

**Comment by rrees** [comment]
@regiskuckaertz ah, would it be clearer to have the comparison with the empty string here to avoid people deleting it as a no-op?

**Comment by regiskuckaertz** [comment]
@rrees yes definitely, that's a code smell. I can raise a PR if you want?

**Comment by rrees** [comment]
@regiskuckaertz that'd be smashing
