### ISSUE TITLE
extra arguments to Range.setEndAfter()

### ISSUE THREAD

**Issue by mindplay-dk** [guardian/scribe#472]
Search the codebase for `.setEndAfter()`, and you'll see `Range.setEndAfter` being called in a few places with what appears to be an extra `0` argument after the node?

According to Mozilla's DOM reference, that method takes one argument:

https://developer.mozilla.org/en-US/docs/Web/API/Range/setEndAfter

**Comment by mindplay-dk** [comment]
There are calls to `Range.setStartAfter` passing an extra second argument as well.

**Comment by rrees** [comment]
I'll check with @OliverJAsh in case of any undocumentated behaviour but it looks like the additional parameters could be removed

**Comment by OliverJAsh** [comment]
:+1:
