### ISSUE TITLE
Undo misplaces the caret/cursor

### ISSUE THREAD

**Issue by paperboyo** [guardian/scribe#478]
Hello,

Undo/Redo is not playing nice with the caret/cursor position (Undos/Redos at the end of a GIF, after placing an extra `s`):

![undo scribe](https://cloud.githubusercontent.com/assets/6032869/14770938/1e5dfa00-0a74-11e6-9eb7-cb6ad7abacb9.gif)

I think Undo/Redo should leave the caret/cursor at the position it was before Undo/Redo was called for.

Regards
Mateusz

**Comment by rrees** [comment]
This is due to our use of a time-based undo, effectively the whole local change is being undone, which is probably right in the majority of cases. Not sure what to do about it right now.

**Comment by paperboyo** [comment]
Thanks! Closing, if that’s what’s expected...
