### ISSUE TITLE
allowBlockElements=false in Safari prevents entering new lines

### ISSUE THREAD

**Issue by danburzo** [guardian/scribe#488]
If you instantiate Scribe with `allowBlockElements=false` in Safari, you're not able to insert new lines with the Enter key. I'm investigating the source of the bug and will propose a PR, but any guidance in the meantime is appreciated!

**Comment by danburzo** [comment]
I have narrowed it down to this piece of code https://github.com/guardian/scribe/blob/master/src/plugins/core/inline-elements-mode.js#L89 and at first brush it seems Safari and Chrome end up with different ranges, and thus the call to `hasContent` returns `true` in Safari (which catches a `<br>` in the process) and `false` in Chrome. 

I'm now investigating why Safari has a different range than Chrome.

**Comment by katebee** [comment]
@danburzo thank you for all the detail on this issue 😄 

❤️ documentation
