### ISSUE TITLE
Pressing Enter while having a selection in inline-mode does not delete the range content

### ISSUE THREAD

**Issue by danburzo** [guardian/scribe#489]
The code that handles inline mode (`allowBlockElements=false`) assumes that when pressing the Enter key, the range is always collapsed. When it happens not to be, the selected characters are not deleted when inserting the new line.

**Comment by danburzo** [comment]
_Note:_ It's also now apparent that the check to see if there's content at the right of the cursor fails in both Chrome and Firefox, i.e. pressing Enter in the middle of a word will insert two `<br>` elements.

**Comment by codeclown** [comment]
Noticed this as well. Any possibility of merging?
