### ISSUE TITLE
NPM releases improvements

### ISSUE THREAD

**Issue by nazar-pc** [guardian/scribe#502]
Currently NPM version contains everything from this repository as is, however examples, tests and utility scripts are not necessary in production (this would greatly decrease download size). Also there is no production builds in NPM version.

So this is an issue with 2 parts:
- [ ] add production builds to NPM release
- [ ] remove everything except production files from NPM release

If you think both features are something you'd like to see I think I can tackle them both and send you a PR. Thoughts?

**Comment by ShaunYearStrong** [comment]
@nazar-pc This is something I've noticed too over the past few days of use. This is definitely an interesting path, and anything to improve the NPM release to at least parity with that of the bower release would be great.

**Comment by shaundillon** [comment]
@nazar-pc If you check out #512 We're moving towards npm only. It'll be ready soon!

**Comment by nazar-pc** [comment]
Better late than never, good to know there is some development in this repository.
Feel free to close this issue if it is obsolete now.
