### ISSUE TITLE
whether consider supporting umd？

### ISSUE THREAD

**Issue by xsbchen** [guardian/scribe#509]
whether consider supporting umd by webpack？

**Comment by danburzo** [comment]
Porting the Scribe codebase to ES6 modules was a pretty straightforward step for us — done by hand in under an hour. Then the modules can be [converted to UMD with Babel](https://babeljs.io/docs/plugins/transform-es2015-modules-umd/) if you need this specific format. I suggest just forking the repo and doing it yourself.

**Comment by xsbchen** [comment]
#83
