### ISSUE TITLE
allow for different block elements

### ISSUE THREAD

**Issue by matthewmueller** [guardian/scribe#89]
right now the library assumes that `<p>` is the desired block element, it'd be great to support other elements along with nested block structures.

**Comment by forresto** [comment]
:+1: I also need to attach metadata to each text/media element. Are there any examples of this working?

**Comment by oyeanuj** [comment]
>At the Guardian, we do support rich text using Scribe. Our content is represented as JSON, and HTML is only used for inline text. Content is broken down into “elements”. For example, you might have:
>image element
text element
embed element
video element
another text element
Non-text elements, such as images, embeds, and videos, are just JSON structures that contain the necessary metadata, i.e. a URL to an image. A text element just contains the HTML for that chunk of text. It will have things such as lists and inline styling, but no images or any other rich media.

>So, we have created an interface that creates this structure seamlessly, as if the user was editing a word document – except with more structure in the [hidden] representation.

@OliverJAsh I was quite curious about how you were doing this since I am thinking of taking the same approach but not sure what the best approach is. Do you essentially have a normalization plugin that takes the markup and matches tags to element above and then creates json based on that?

Could you share your approach or is that already part of library/plugin ecosystem?

Thanks so much!

**Comment by theefer** [comment]
The CMS doesn't use Scribe to represent and edit anything but text.

It's more like:

```
CMS
  [scribe instance for text paragraphs]
  [image editing block]
    [scribe instance for editing image caption]
    [textarea for editing image alt text]
  [scribe instance for text paragraphs]
  [video embed editing block]
    [scribe instance for editing video caption]
  [scribe instance for text paragraphs]
```

![image](https://cloud.githubusercontent.com/assets/36964/12140997/e84bae46-b463-11e5-8eb4-a5216065a780.png)

Hope this makes it a little more clear.

**Comment by oyeanuj** [comment]
@theefer Thanks for the response! So if I understand it correctly, the image and video embeds don't necessarily deal with Scribe and are just different modules/components interspersed? And does the CMS support any drag and drop between the text, image or video embeds?

**Comment by theefer** [comment]
> So if I understand it correctly, the image and video embeds don't necessarily deal with Scribe and are just different modules/components interspersed?

Yes.

> And does the CMS support any drag and drop between the text, image or video embeds?

Not currently, you have to use up/down/top/bottom arrows on the image/video/etc elements to move them around. There is some extra code that splits text elements so you always move media up/down individual paragraphs. You can also *drop* images onto empty lines using some other code handlers, which end up as an image element where you dropped it (again splitting the text element).

Drag and drop of elements around paragraphs is possible, but we haven't implemented it yet.

**Comment by oyeanuj** [comment]
@theefer Appreciate your patience and thanks for your helpful responses :) 

Part of me likes the clean separation between text and all other medias. Just to make sure I understand the CMS approach, and that I am on the right path, does the following sound reasonable - 

My aims are to be able to drag and drop image, video, or add a link and have that turn into a rich preview. (Paragraph drag and drop would be a nice bonus).

Given that, here is how I am thinking it would work:

1. Initialize the first `scribe` instance and a user can enter text. 
2. If they click on a button to add image or drag and drop one in the editor, it will add it after the 'editor' in the DOM and then auto-generate the next `scribe` instance.
3. This will allow for simple drag and drop using external libraries around `scribe` instances.
4. If someone copy-pastes a url in, and I want to turn it into an link preview in-place, it will essentially follow Step 2.

If that is correct, two more questions -

- Is the creating of new `scribe` instance on the fly the recommended approach or is there a more optimal approach?

- 
> There is some extra code that splits text elements so you always move media up/down individual paragraphs. 

Is this available as a plugin? Or could you share the logic that you use and I could create a plugin for it?


Thanks again!

**Comment by mindplay-dk** [comment]
> Is this available as a plugin?

@oyeanuj Would this make sense as a plugin?

It's not really an editor feature - it's more like the editor is a feature of that interface?

I'm working on something similar, and that's the approach I'm taking - we call them "parts" to avoid ambiguity with HTML "elements", each has a dedicated "driver" that creates and populates the editor interface for it. Each of those drivers create and manage the interface for a particular type of part, the user can add/remove parts, and some of the part drivers happen to use Scribe to create rich content editors, but that seems like a detail. So I'm not sure how this would make sense as a plugin?
